### ISSUE TITLE
Need to account for * at the end of max stats.

### ISSUE THREAD

**Issue by AardCentral** [danj2k/aardwolf-plugins#1]
On line 295, change:

 _, _, current, maximum = string.find(v, "(%d+)%s+(%d+)$")

to

 _, _, current, maximum = string.find(v, "(%d+)%s+(%d+)%*?$")

When you're at max stats, the output is:   123   123*

**Comment by danj2k** [comment]
@AardCentral thanks for posting this! I've committed your fix, can you verify that it works as expected? As unfortunately my character doesn't have enough trains to train to max stats.

**Comment by AardCentral** [comment]
As long as you made the change I posted, it should be good. I made the change locally myself and it worked without issue.
