### ISSUE TITLE
won't turn on, gives errors

### ISSUE THREAD

**Issue by bronniebambam** [danj2k/aardwolf-plugins#4]
![danj sv](https://user-images.githubusercontent.com/126620914/221983987-b24e3684-2b82-4923-a481-9e39e1a47d40.JPG)

https://imgur.com/a/Lc6DIf8

**Comment by danj2k** [comment]
Hello! Please can you take a screenshot of what the output of the MUD `train` command looks like for you? It's likely this is happening because my triggers are not set up correctly, but I'd need to see the `train` output you get in order to adjust this.

**Comment by bronniebambam** [comment]
![train command](https://user-images.githubusercontent.com/126620914/222223380-3c64803a-bc08-4e1d-8dd4-e92e0069ee71.JPG)

**Comment by danj2k** [comment]
I've uploaded a new version of the plugin. Please can you remove the old version from MUSHclient, then overwrite the plugin file with the new version, and add it back in again to see if it will work?

**Comment by bronniebambam** [comment]
it seems to be working now, thank you!

**Comment by danj2k** [comment]
Thanks for letting me know the issue is fixed :)
